# Generated by Django 5.2.16 on 2026-07-23 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('week_start', models.CharField(default='monday', max_length=10)),
                ('site_name', models.CharField(default='PlasticKothay', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=512)),
                ('logo_provider', models.CharField(blank=True, max_length=32)),
                ('logo_external_id', models.CharField(blank=True, max_length=255)),
                ('map_lat', models.FloatField(blank=True, null=True)),
                ('map_lon', models.FloatField(blank=True, null=True)),
                ('map_zoom', models.IntegerField(default=12)),
                ('flags', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_config',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='site_config_singleton')],
            },
        ),
    ]
