# Generated by Django 5.2.16 on 2026-07-23 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0002_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('criteria', models.CharField(choices=[('posts_approved', 'Posts approved'), ('likes_received', 'Likes received'), ('likes_given', 'Likes given'), ('points_total', 'Total points')], max_length=32)),
                ('threshold', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'badge_rule',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_code', models.CharField(max_length=64)),
                ('earned_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_badge',
                'indexes': [models.Index(fields=['user'], name='user_badge_user_id_ce3b6e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'badge_code'), name='uniq_badge_per_user')],
            },
        ),
    ]
