# Generated by Django 5.2.16 on 2026-07-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0003_badgerule_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
