# Generated by Django 5.2.16 on 2026-07-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0004_post_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_external_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
